### ISSUE TITLE
Figure 7.13 line 22

### ISSUE THREAD

**Issue by Aznaveh** [tgmattso/OmpCommonCore#1]
Three variables in printf but four %l...
I get a warning and wrong run_time
That line works like this for me:
printf("pi = %lf, %ld steps %lf secs\n ",pi, num_steps, run_time);

**Comment by helenhe40** [comment]
Thanks for reporting the bug.   I have fixed it with:

printf("pi = %lf, with %ld steps, in %lf secs\n ", pi, num_steps, run_time);
