### ISSUE TITLE
private variable

### ISSUE THREAD

**Issue by Mealoore** [tgmattso/OmpCommonCore#2]
When  reading your book, " The OpenMP Common Core", I have a question about this expression "#pragma omp parallel firstprivate(vptr[0:1000:1])"  in the last few paragraphs of chapter 6, is there a syntax, "vptr[0:1000:1]" in c/c++ ?

**Comment by tgmattso** [comment]
The array slicing notation in OpenMP is not available in C or C++ (though C++ is moving so fast these days, it wouldn't surprise me if there is some way to do it in one of the more recent releases of the C++ spec).   

It took me  a while to get used to the way this is expressed in OpenMP.   I prefer [initial, final, stride] but the standard went with [initial: length: stride].  That feels weird to me, but that's they way it was defined so we have to live with it.

**Comment by Mealoore** [comment]
so, isn't this expression  used in c/c++?and where is it used? sorry, i just have experience with  c/c++.

**Comment by Mealoore** [comment]
so, isn't this expression  used in c/c++?and where is it used? sorry, i just have experience with  c/c++.

**Comment by tgmattso** [comment]
This expression is used in an OpenMP pragma in C and C++.   The notation is an OpenMP notation.  It is not a C/C++ notation.  I can use

      #pragma omp parallel firstprivate(A[0:100:3])

But I can't use

     *B = (float*) malloc(N*sizeof(float));
       B = A[0:100:3];

In other words, the notation works on the OpenMP pragma because the OpenMP parser knows what to do with it.  The array notation, however, is not part of the C (or C++) programming language.

Does that make sense?  Or am I still missing what you are asking?

**Comment by Mealoore** [comment]
Thanks for your example! And I got you. But when I test my code
```cpp
  int *vptr;
  vptr = (int *)malloc(10*sizeof(int));
  omp_set_num_threads(4);
  #pragma omp parallel firstprivate(vptr[0:10:1])
  {
    printf("%x %x\n",vptr,&vptr);
  }
```
the compiler gives an error, `error: expected ‘)’ before ‘[’ token
   #pragma omp parallel firstprivate(vptr[0:10:1])`. That's just what I wanted to ask. I'm sorry that I didn't make it clear.
My environment is Ubuntu 18.04.

**Comment by Mealoore** [comment]
Excuse me, do you have an idea about my question, the error from the compiler? Thanks a lot.

**Comment by tgmattso** [comment]
This week is SC21.  I am a bit busy with tutorials on OpenMP.   On first glance, this should work.  I don't know what's going on.  I'll check and get back to you

**Comment by Mealoore** [comment]
> This week is SC21. I am a bit busy with tutorials on OpenMP. On first glance, this should work. I don't know what's going on. I'll check and get back to you

Thanks  for your reply in your busy schedule.Go ahead！You can do it！

**Comment by Mealoore** [comment]
Excuse me, do you have an idea about my question, the error from the compiler? Thanks a lot.

**Comment by Mealoore** [comment]
Excuse me, do you have an idea about my question, the error from the compiler? Thanks a lot.

**Comment by tgmattso** [comment]
OK, I have figured this out.  The book is wrong.    Errors in a book are inevitable (this is my fifth book ... and I have concluded it is impossible not to screw up at at least a few times in a book).  We tried to test every piece of code in the book.  Clearly we failed to do this for the code on page 119.   In my opinion, this is an error in the specification.    But that doesn't get me off the hook.

So here is the fix.   You cannot use an array section notation in a data environment clause unless the specification specifically says it is allowed to do so.   Array sections cannot be used with private or firstprivate.  They can be used with reduction but only for a contiguous slice of the array meaning the form of an array section with a stride is not supported with the reduction.

I am really sorry for this confusion.   I can pass an array "on the stack" into first private:

        int A[N];
        #pragma omp parallel firstprivate

This will create an array with the name A and copy the original array into that array for each thread.

I can pass a pointer

       int *vptr;
       #pragma omp parallel firstprivate(vptr)


That will give each thread its own pointer named vptr but for each thread, vptr points to the same block of memory.

I cannot, however, use the array section notation with firstprivate.   I do not agree with this situation in the specification, but I can see why we did not choose to support this case.   Think about it .. if you create a private array and enable it for independent writing by each thread, when the construct in question completes, that array goes out of scope and all the writes into the array are lost.   Hence, in most cases where you might think you want firstprivate on an array section, it would be an error to do so.   If you want to see the results of all those writes, you need a shared block of memory.

**Comment by Mealoore** [comment]
Thanks for spending much time on this question, errors are inevitable. And I just want to know what I never meet. :smiley:
