### ISSUE TITLE
Slide 105, recursive Fibonacci

### ISSUE THREAD

**Issue by paulcaprioli** [tgmattso/OmpCommonCore#8]
The Fibonacci example warns readers it is an inefficient O(n^2) implementation.
I believe it is much slower, O(2^n).

If you like, you can also lowercase the first letter of "Int main()".

**Comment by paulcaprioli** [comment]
Slide 227: spelling error "OMP_NUM_THREDS"

**Comment by tgmattso** [comment]
Thank you.  You are correct all counts. I will update the slides.
